



















module.exports = connectToDatabase;}  }    console.error('Error connecting to database:', error);  } catch (error) {    return collection;    const collection = db.collection(collectionName);    const db = client.db(dbName);    console.log('Connected to database');    await client.connect();  try {async function connectToDatabase() {const collectionName = process.env.COLLECTION_NAME;const dbName = process.env.DB_NAME;const client = new MongoClient(process.env.MONGODB_URI);const { MongoClient } = require('mongodb');require('dotenv').config();